import Head from 'next/head';
import Link from 'next/link';

import styles from '../styles/Home.module.scss';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href={'/users'}>
          <div className={styles.main__link}>Go to users list</div>
        </Link>
      </main>
    </div>
  );
}
